version: "3.3"
services:

  # Container for development purposes
  facetorch-dev:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ./:/opt/facetorch
    ports:
      - "8080:8080"

  facetorch-dev-gpu:
      build:
        context: .
        dockerfile: ./docker/Dockerfile.dev.gpu
      volumes:
        - ./:/opt/facetorch
      ports:
        - "8080:8080"
      shm_size: 8gb
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [ gpu ]

  facetorch-dev-example:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ./:/opt/facetorch
    ports:
      - "8080:8080"
    entrypoint: ["conda", "run", "--no-capture-output", "-n", "env", "python", "scripts/example.py"]

  facetorch-dev-tests:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ./:/opt/facetorch
    ports:
      - "8080:8080"
    entrypoint: ["conda", "run", "--no-capture-output", "-n", "env", "pytest", "-v"]