version: "3.3"
services:

  # Container for development purposes
  facetorch-dev:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ./:/opt/facetorch
    entrypoint: ["/bin/bash"]

  facetorch-dev-gpu:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev.gpu
    volumes:
      - ./:/opt/facetorch
    shm_size: 8gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [ gpu ]
    entrypoint: ["/bin/bash"]

  facetorch-tests:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.tests
    volumes:
      - ./:/opt/facetorch
    entrypoint: ["conda", "run", "--no-capture-output", "-n", "env", "pytest", "-v", "--cov=facetorch", "--cov-report=term", "--cov-fail-under=95"]

  facetorch-dev-example:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ./:/opt/facetorch
    entrypoint: ["conda", "run", "--no-capture-output", "-n", "env", "python", "scripts/example.py"]