_target_: facetorch.analyzer.predictor.FacePredictor

downloader:
  _target_: facetorch.downloader.DownloaderGDrive
  file_id: 10b4h5OgKPflHiVf9P2G0vFtLVPSbf1tV
  path_local: /opt/facetorch/models/torchscript/predictor/au/1/model.pt # str

device:
  _target_: torch.device
  type: ${analyzer.device} # str

preprocessor:
  _target_: facetorch.analyzer.predictor.pre.PredictorPreProcessor
  transform:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.Resize
        size: [224, 224] # List[int]
      - _target_: torchvision.transforms.Normalize
        mean: [0.485, 0.456, 0.406] # List[float]
        std: [0.229, 0.224, 0.225] # List[float]
  device: 
    _target_: torch.device
    type: ${analyzer.predictor.au.device.type}
  optimize_transform: ${analyzer.optimize_transforms}
  reverse_colors: False # bool

postprocessor:
  _target_: facetorch.analyzer.predictor.post.PostMultiLabel
  transform: None
  device: 
    _target_: torch.device
    type: ${analyzer.predictor.au.device.type}
  optimize_transform: ${analyzer.optimize_transforms}
  dim: 1
  threshold: 0.5
  labels: ["inner_brow_raiser", "outer_brow_raiser", "brow_lowerer", "cheek_raiser", "lid_tightener", "upper_lip_raiser", "lip_corner_puller", "dimpler", "lip_corner_depressor", "chin_raiser", "lip_tightener", "lip_pressor"] # List
