name: Docker Compose CI

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Test
        run: docker compose run facetorch pytest -v --cov=facetorch --cov-report=term --cov-fail-under=95
