name: Docker Compose CI

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and test
        run: docker compose -f docker-compose.dev.yml run -d facetorch-dev pytest -v --cov=facetorch --cov-report=term --cov-fail-under=95
