name: Docker push images

on:
  pull_request_target:
    branches: [ "main" ]
    types:
      - closed

permissions:
  contents: read

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Info
    - run: |
        echo The PR was merged
    - uses: actions/checkout@v2
    - name: Docker compose push facetorch
      run: docker compose push facetorch
    - uses: actions/checkout@v2
    - name: Docker compose push facetorch-gpu
      run: docker compose push facetorch-gpu