name: Docker Compose CI

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the stack
        run: docker compose -f docker-compose.dev.yml build facetorch-dev
      - name: Test
        run: docker compose -f docker-compose.dev.yml run facetorch-dev pytest -v --cov=facetorch --cov-report=term --cov-fail-under=95
      - name: Stop containers
        if: always()
        run: docker compose down
